### ISSUE TITLE
Please check it out.

### ISSUE THREAD

**Issue by Amateurmonkey** [ECreates/py-mandelbrot#2]
I am a Python beginner, but I have encountered some problems in my studies. Occasionally, I will be able to contact me, or be able to be my teacher and teach me!
Thank you.
                                                                                                                                ----moran

**Comment by EthanDP** [comment]
This isn't really an issue with the repository so I'm closing it, but if you have any questions about learning Python feel free to hit me up and I'll show you some resources that I used to learn.
