### ISSUE TITLE
Please check it out.

### ISSUE THREAD

**Issue by Amateurmonkey2** [ECreates/py-mandelbrot#3]
I am a Python beginner, but I have encountered some problems in my studies. Occasionally, I will be able to contact me, or be able to be my teacher and teach me!
Thank you.
----moran

**Comment by EthanDP** [comment]
I am a Python beginner, but I have encountered some problems in my studies. Occasionally, I will be able to contact me, or be able to be my teacher and teach me!
Thank you.
----moran
